# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e5f9973f109380c6588c49162a9f7eb4c55c52b701f9764f814d8d6cf950c1cca7af8623746f90b0150e30eabb1ef74d21993c4f851e5936e5b17c1e72a4e89

test:
  secret_key_base: a19488172a9b027882008a059081c4e8d41c078880c8a48d34c9ba4a736f238dc865ab5a8f4289e20d264145d758ff1b4b0c1493c0e47a463dd511050058bb57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
